package com.dbrsn.scalajs.react.sortablehoc

import scala.collection.mutable.ListBuffer

/**
  * A change in index of an item generated by dragging
  *
  * @param oldIndex The item's old index
  * @param newIndex The item's new index
  */
final case class IndexChange(oldIndex: Int, newIndex: Int) {
  def updatedList[A](l: List[A]): List[A] = {
    val lb = ListBuffer(l: _*)
    val e = lb.remove(oldIndex)
    lb.insert(newIndex, e)
    lb.toList
  }
}
